### ISSUE TITLE
For info : double carriage_return between segments will crash hl7.create_ack method

### ISSUE THREAD

**Issue by tizbecool** [johnpaulett/txHL7#10]
Hello,

I had to deal with hl7 message in production environnement from professional medcare company and some introduce new_line segment separator or double new_line or double_carriage. Since I can't make them change their standard i had to filter incoming message with this

raw_message = re.sub(r"[\n\r]+", self.carriage_return, raw_message) 
 
in txHL7.dataReceived, at start of the loop

There is a commit in my fork but code is messy for the moment ^^

this is the kind of exception I got before fix:

2015-03-10 16:27:43+0100 [MinimalLowerLayerProtocol,0,10.1.220.5] Unhandled error in Deferred:
2015-03-10 16:27:43+0100 [MinimalLowerLayerProtocol,0,10.1.220.5] Unhandled Error
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 221, in _dataReceived
        rval = self.protocol.dataReceived(data)
      File "build/bdist.linux-x86_64/egg/txHL7/mllp.py", line 65, in dataReceived

      File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 317, in addErrback
        errbackKeywords=kw)
      File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 295, in addCallbacks
        self._runCallbacks()
    --- <exception caught here> ---
      File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
        current.result = callback(current.result, *args, **kw)
      File "build/bdist.linux-x86_64/egg/txHL7/mllp.py", line 57, in onError

      File "/home/*****/bin/EmgHL7Server/src/EmgHL7Server.tac", line 42, in err
        return self.ack(ack_code='AR')
      File "/home/*****/bin/EmgHL7Server/src/EmgHL7Server.tac", line 37, in ack
        return unicode(self.message.create_ack(ack_code))
      File "build/bdist.linux-x86_64/egg/hl7/containers.py", line 455, in create_ack

      File "build/bdist.linux-x86_64/egg/hl7/containers.py", line 156, in segment

      File "build/bdist.linux-x86_64/egg/hl7/containers.py", line 173, in segments

      File "build/bdist.linux-x86_64/egg/hl7/containers.py", line 173, in <genexpr>

    exceptions.IndexError: string index out of range

**Comment by johnpaulett** [comment]
Can you find any references to multiple carriage returns being a normal or per-spec behavior?  

If it is, we should include this in core. If it is not, I don't think we should munge the data with a regex.

The good news is that we already have a hook to put custom logic like this.  If you create your own AbstractReceiver subclass, you could override `parseMessage` to clean the double \r before calling `super(...).parse_message(modified_message)`.

See http://txhl7.readthedocs.org/en/latest/api.html#txHL7.receiver.IHL7Receiver.parseMessage and http://txhl7.readthedocs.org/en/latest/custom-receiver.html#example-receiver for rough examples.

**Comment by tizbecool** [comment]
You're right (as always :) ) !! parseMessage is the place for this stuff !!

I found nothing about double carriage returns or newline or double newline as far as I look for it. I think this is just some altered specs implementation of french big companies (4 for the moment) with I have to exchange HL7  messages. They usually adapt the spec for your needs or convenience aka windows implementation with newline instead or carriage returns.

Thanks for your response

**Comment by johnpaulett** [comment]
Good to know -- I feel your pain with getting "adapted" HL7...

I'm going to close the issue for now.  But if you find corner cases where we don't follow the spec or we could offer additional hooks for gracefully handling odd data, please bring them up.

Thanks!
